"""
Dark Strategist Agent — Notifier
Slack webhook + GitHub Issues for DOMAIN_EXPANSION_RECOMMENDED events.
Version: 2.7.0
"""

import json
import requests
from datetime import datetime


class SlackNotifier:
    def __init__(self, webhook_url: str, channel: str):
        self.webhook_url = webhook_url
        self.channel = channel

    def send_domain_expansion(self, routing: dict) -> bool:
        domain = routing.get("domain", "Unknown")
        confidence = routing.get("confidence", "N/A")
        timestamp = routing.get("timestamp", datetime.utcnow().isoformat())
        key_points = routing.get("key_verification_points", [])
        suggested_file = f"system_prompt_{domain.lower().replace(' ', '_')}.md"
        points_text = "\n".join([f"  → {p}" for p in key_points]) if key_points else "  (none extracted)"

        payload = {
            "channel": self.channel,
            "username": "Dark Strategist — Domain Monitor",
            "icon_emoji": ":mag:",
            "blocks": [
                {"type": "header", "text": {"type": "plain_text", "text": "🔍 DOMAIN_EXPANSION_RECOMMENDED"}},
                {"type": "section", "fields": [
                    {"type": "mrkdwn", "text": f"*Detected Domain:*\n{domain}"},
                    {"type": "mrkdwn", "text": f"*Confidence:*\n{confidence}"},
                    {"type": "mrkdwn", "text": f"*Prompt Used:*\nDYNAMIC_TEMPORARY"},
                    {"type": "mrkdwn", "text": f"*Timestamp:*\n{timestamp}"},
                ]},
                {"type": "section", "text": {"type": "mrkdwn",
                    "text": f"*Key Verification Points:*\n{points_text}"}},
                {"type": "section", "text": {"type": "mrkdwn",
                    "text": f"*Recommended Action:*\nCreate `prompts/{suggested_file}`"}},
                {"type": "context", "elements": [{"type": "mrkdwn",
                    "text": "Dark Strategist Agent v2.7.0 | github.com/JARPClaude/dark-strategist-agent"}]}
            ]
        }

        try:
            response = requests.post(self.webhook_url,
                data=json.dumps(payload),
                headers={"Content-Type": "application/json"}, timeout=10)
            if response.status_code == 200:
                print("✅ Slack notification sent")
                return True
            print(f"⚠️  Slack failed: {response.status_code}")
            return False
        except Exception as e:
            print(f"⚠️  Slack error: {e}")
            return False


class GitHubNotifier:
    def __init__(self, token: str, owner: str, repo: str):
        self.token = token
        self.owner = owner
        self.repo = repo

    def create_domain_expansion_issue(self, routing: dict) -> bool:
        domain = routing.get("domain", "Unknown")
        confidence = routing.get("confidence", "N/A")
        timestamp = routing.get("timestamp", datetime.utcnow().isoformat())
        key_points = routing.get("key_verification_points", [])
        suggested_file = f"system_prompt_{domain.lower().replace(' ', '_')}.md"
        points_md = "\n".join([f"- {p}" for p in key_points]) if key_points else "_None extracted_"

        title = f"[DOMAIN_EXPANSION] New domain detected: {domain}"
        body = f"""## DOMAIN_EXPANSION_RECOMMENDED

Auto-generated by Dark Strategist Router Agent.

| Field | Value |
|-------|-------|
| **Detected Domain** | {domain} |
| **Confidence** | {confidence} |
| **Prompt Used** | DYNAMIC_TEMPORARY |
| **Detected At** | {timestamp} |

### Key Verification Points
{points_md}

### Recommended Action
Create `prompts/{suggested_file}` with the key points above.

---
_Auto-generated by Dark Strategist Agent v2.7.0_
"""

        headers = {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json",
            "Content-Type": "application/json"
        }
        payload = {"title": title, "body": body,
                   "labels": ["domain-expansion", "new-prompt", "auto-generated"]}

        try:
            response = requests.post(
                f"https://api.github.com/repos/{self.owner}/{self.repo}/issues",
                data=json.dumps(payload), headers=headers, timeout=15)
            if response.status_code == 201:
                print(f"✅ GitHub Issue created: {response.json().get('html_url', '')}")
                return True
            print(f"⚠️  GitHub Issue failed: {response.status_code}")
            return False
        except Exception as e:
            print(f"⚠️  GitHub error: {e}")
            return False
